[package]
name = "aoc2015"
version = "0.1.0"
authors = ["tuffing <logan.orr@tuffing.co.nz>"]
edition = "2018"

[dependencies]
regex = "1"
fancy-regex = "0.1.0"
rust-crypto = "0.2.35"
serde_json = "1.0"
